### PR TITLE
Allow custom resolutions in fullscreen mode.

### PR DESCRIPTION
**Pull request by fak98**
A cheap workaround to a proper HiDPI mode.

### CODE REVIEW

**Comment by Cheezmeister** [comment]
Looks alright at a glance. What's the use case here?

**Comment by fak98** [comment]
Attempting to play it on a laptop with a 4k screen is tough, specially for little people

**Comment by Cheezmeister** [comment]
Thanks Fahad. I think we ideally want to address this problem with proper vector scaling. Would you kindly attach a screenshot or two to #3 please?

**Comment by Cheezmeister** [comment]
Could you also please document this new item in [data/missions/options](https://github.com/tux4kids/tuxmath/blob/master/data/missions/options)

**Pull request merged**
